# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)

User.create(email: "admin@wojzag.pl", firstname: "Grzegorz", lastname: "Brzęczyszczykiewicz", password: "12345678", admin: true)
User.create(email: "jkowalski@wojzag.pl", firstname: "Jan", lastname: "Kowalski", password: "12345678")
User.create(email: "jacksparrow@wojzag.pl", firstname: "Jack", lastname: "Sparrow", password: "12345678")
User.create(email: "kingarthur@wojzag.pl", firstname: "Arthur", lastname: "King", password: "12345678")
User.create(email: "marcopolo@wojzag.pl", firstname: "Marco", lastname: "Polo", password: "12345678")

Category.create(name: "Role Playing Games")
Category.create(name: "Real Time Strategies")
Category.create(name: "Race Games")
Category.create(name: "First Person Shooters")
Category.create(name: "Survivals")

Product.create(title: "GTA V", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris porttitor diam erat, a ullamcorper arcu tempor nec. Donec elementum, magna id fringilla hendrerit, sem nunc pharetra risus, egestas viverra metus nisi ac arcu. Nulla consectetur laoreet urna nec varius. Sed interdum varius tellus, vel dictum tortor maximus a. Proin ornare malesuada tortor, quis vehicula nulla. Suspendisse consequat felis id pretium finibus. Mauris et mauris volutpat lacus venenatis luctus in nec eros. Phasellus vel auctor nulla, at fringilla nisi. Sed porttitor nisl ut porta egestas. Donec ut volutpat odio. Sed accumsan velit non erat efficitur, quis vestibulum nisi congue.", price: 99.99, category_id: 4, user_id: 2)
Product.create(title: "Baldur's Gate 2: Shadow of Amn", description: "Maecenas pretium pretium sem, eget pellentesque diam blandit eu. Vivamus at mollis eros, at imperdiet nulla. Integer nec tristique quam. Aenean nec faucibus tortor. Mauris at augue fermentum neque fringilla feugiat non nec sapien. Sed nec vestibulum justo. Duis commodo nibh elit, sed mollis mi varius non. Maecenas eu mi lacus.", price: 19.99, category_id: 1, user_id: 3)
Product.create(title: "The Witcher 3: Wild Hunt", description: "Etiam tincidunt eget mauris eu consequat. Aliquam suscipit facilisis diam, eu consectetur quam. Phasellus congue velit sed ligula consectetur facilisis. Nullam odio leo, rhoncus vitae nisi at, mattis tincidunt ex. Curabitur tincidunt ornare pellentesque. Praesent auctor nibh in lorem iaculis, eu pretium diam scelerisque. Vivamus ac condimentum purus. Fusce augue velit, pretium id diam et, elementum fringilla mi. Cras id orci quis est fringilla gravida sed vel dolor.", price: 49.99, category_id: 1, user_id: 4)
Product.create(title: "DayZ Standalone", description: "Nulla posuere arcu non placerat congue. Curabitur tempus ante faucibus mauris rutrum sodales. Donec eget ex volutpat, mollis nunc ac, viverra tortor. In egestas fringilla tellus ut vulputate. Nullam nec nisl nulla. Sed tempus sapien nec risus interdum ornare. Sed non arcu quis sapien sollicitudin laoreet. Ut euismod ligula nisi, a volutpat diam euismod vitae. Sed rutrum in tellus et pharetra. Integer sed cursus enim. Nunc a ligula quam. Aliquam pellentesque nulla orci, sit amet finibus ante ultricies eu. Nulla ac rhoncus neque, quis condimentum tellus.", price: 90, category_id: 5, user_id: 2)
Product.create(title: "Arma II", description: "Vestibulum a nisi ex. Pellentesque tristique eros et sapien viverra scelerisque. Donec quis libero ut nulla finibus condimentum sed ut dolor. Fusce sed placerat turpis, et euismod eros. Pellentesque facilisis ipsum eget arcu auctor ornare eget eget felis. Aliquam erat volutpat. Praesent nulla mauris, auctor nec dignissim nec, tincidunt ut nibh. Praesent non elementum odio, ut vehicula leo. Sed elementum ligula vitae sodales consequat.", price: 69.99, category_id: 4, user_id: 4)
Product.create(title: "Minecraft", description: "Donec felis ipsum, volutpat non molestie non, commodo quis leo. Curabitur ut nulla dolor. Nullam tincidunt nulla hendrerit dui malesuada, non auctor lectus tincidunt. Vestibulum consequat mi non augue mollis, sit amet sollicitudin magna varius. Vivamus sit amet nulla dolor. Etiam ac sodales ipsum, at laoreet nisl. Nullam congue lacus arcu, et euismod elit dapibus at. Morbi sit amet nisl imperdiet, auctor ipsum ac, vestibulum velit. Sed mattis metus sit amet porta molestie.", price: 65, category_id: 5, user_id: 5)
Product.create(title: "Mario Carts", description: "Nulla eget elit vel ante dignissim venenatis a vel ante. Praesent ac ipsum erat. Nullam risus tellus, lacinia et massa ultricies, mattis mollis sapien. In fringilla tortor vel dui consequat ornare. Curabitur id viverra neque. Fusce iaculis, lectus quis tempor pharetra, ipsum purus fringilla sem, ut dictum augue enim nec elit. Integer posuere faucibus lacus non interdum. Nunc vel convallis leo. Vestibulum eu facilisis dolor, quis varius lectus. Aliquam in feugiat risus, vel varius ex. Quisque non metus eget orci consequat sagittis. Sed pellentesque sit amet nisl eu vehicula.", price: 30, category_id: 3, user_id: 5)
Product.create(title: "Age of Empires 3", description: "Praesent eu sollicitudin ipsum. Quisque vel magna libero. Proin eu ipsum orci. Etiam finibus tempus varius. Maecenas pellentesque erat magna, id elementum nunc iaculis eget. Aliquam tincidunt eu sapien quis tristique. Cras sit amet neque sit amet odio posuere vestibulum id ac nunc. Mauris tincidunt bibendum sapien at consectetur. Morbi posuere sodales elit eu dictum. Praesent id lectus vel ex euismod mollis sed a augue.", price: 19.99, category_id: 2, user_id: 3)
Product.create(title: "Starcraft 2", description: "Sed felis diam, consectetur vitae elit vel, eleifend rutrum elit. Maecenas molestie vestibulum dolor eget hendrerit. Suspendisse a volutpat felis. Donec egestas vel nunc ac blandit. Phasellus consectetur tortor tincidunt mauris tempus tristique. Fusce id iaculis neque. Etiam luctus massa id erat malesuada, ac sagittis magna malesuada. Sed pellentesque, dui vel semper varius, velit magna aliquam mauris, id posuere elit massa sed justo. Nunc in risus ullamcorper, iaculis ipsum a, luctus lacus.", price: 54.99, category_id: 2, user_id: 3)
Product.create(title: "Burnout Paradise", description: "Cras luctus urna ex, sit amet vehicula lectus tincidunt non. Mauris maximus dolor lorem, sed gravida neque tincidunt sit amet. Pellentesque non maximus nulla, eu imperdiet tortor. Phasellus est lectus, interdum at lectus vitae, blandit tincidunt tellus. Quisque non magna eget justo feugiat cursus in in eros. Mauris bibendum volutpat magna eu ultrices. Praesent nisi eros, pretium sagittis lorem id, efficitur pharetra dolor.", price: 29.99, category_id: 3, user_id: 2)

Review.create(content: "Vestibulum in nisi nibh. Praesent imperdiet dolor eros, vitae accumsan dolor auctor non. Vestibulum ex est, dignissim sed sem non, blandit placerat urna. Proin consectetur viverra euismod. Sed laoreet ante et nisi dapibus euismod. Sed congue purus a congue elementum.", rating: 5, product_id: 1, user_id: 2)
Review.create(content: "Vestibulum in nisi nibh. Praesent imperdiet dolor eros, vitae accumsan dolor auctor non. Vestibulum ex est, dignissim sed sem non, blandit placerat urna. Proin consectetur viverra euismod. Sed laoreet ante et nisi dapibus euismod. Sed congue purus a congue elementum.", rating: 4, product_id: 2, user_id: 2)
Review.create(content: "Nulla iaculis feugiat quam in cursus. Sed dictum hendrerit urna, nec accumsan lacus ullamcorper euismod. Nulla vitae facilisis diam.", rating: 4, product_id: 3, user_id: 2)
Review.create(content: "Nulla iaculis feugiat quam in cursus. Sed dictum hendrerit urna, nec accumsan lacus ullamcorper euismod. Nulla vitae facilisis diam.", rating: 1, product_id: 4, user_id: 3)
Review.create(content: "Nulla iaculis feugiat quam in cursus. Sed dictum hendrerit urna, nec accumsan lacus ullamcorper euismod. Nulla vitae facilisis diam.", rating: 5, product_id: 5, user_id: 3)
Review.create(content: "Aliquam neque augue, pharetra ut sagittis facilisis, malesuada a risus. Curabitur finibus erat bibendum, pretium urna ac, dignissim enim. Duis semper nulla sed magna tempor pulvinar.", rating: 5, product_id: 6, user_id: 3)
Review.create(content: "Aliquam neque augue, pharetra ut sagittis facilisis, malesuada a risus. Curabitur finibus erat bibendum, pretium urna ac, dignissim enim. Duis semper nulla sed magna tempor pulvinar.", rating: 2, product_id: 7, user_id: 4)
Review.create(content: "Aliquam neque augue, pharetra ut sagittis facilisis, malesuada a risus. Curabitur finibus erat bibendum, pretium urna ac, dignissim enim. Duis semper nulla sed magna tempor pulvinar.", rating: 3, product_id: 8, user_id: 4)
Review.create(content: "Aliquam neque augue, pharetra ut sagittis facilisis, malesuada a risus. Curabitur finibus erat bibendum, pretium urna ac, dignissim enim. Duis semper nulla sed magna tempor pulvinar.", rating: 4, product_id: 9, user_id: 5)
Review.create(content: "Integer ultricies, nulla nec viverra ullamcorper, turpis ipsum dignissim urna, non porttitor tellus odio id sapien. Pellentesque et magna in turpis varius facilisis.", rating: 4, product_id: 1, user_id: 5)
Review.create(content: "Integer ultricies, nulla nec viverra ullamcorper, turpis ipsum dignissim urna, non porttitor tellus odio id sapien. Pellentesque et magna in turpis varius facilisis.", rating: 5, product_id: 1, user_id: 4)
Review.create(content: "Duis blandit lorem id est sagittis, in ullamcorper lorem porta. In id tincidunt est. Interdum et malesuada fames ac ante ipsum primis in faucibus.", rating: 5, product_id: 3, user_id: 5)
Review.create(content: "Duis blandit lorem id est sagittis, in ullamcorper lorem porta. In id tincidunt est. Interdum et malesuada fames ac ante ipsum primis in faucibus.", rating: 4, product_id: 3, user_id: 3)
Review.create(content: "Duis blandit lorem id est sagittis, in ullamcorper lorem porta. In id tincidunt est. Interdum et malesuada fames ac ante ipsum primis in faucibus.", rating: 3, product_id: 7, user_id: 2)
Review.create(content: "Duis sollicitudin metus feugiat eleifend accumsan. Maecenas quis est vitae velit ornare scelerisque nec nec est. Suspendisse rutrum, odio vitae sollicitudin egestas, nunc risus finibus diam, id gravida enim quam at eros.", rating: 4, product_id: 7, user_id: 2)
Review.create(content: "Duis sollicitudin metus feugiat eleifend accumsan. Maecenas quis est vitae velit ornare scelerisque nec nec est. Suspendisse rutrum, odio vitae sollicitudin egestas, nunc risus finibus diam, id gravida enim quam at eros.", rating: 4, product_id: 8, user_id: 3)
Review.create(content: "In eu eros eu ex malesuada condimentum. Nunc ut lacus consectetur, pretium nisl et, vehicula sapien. Cras mollis quam mattis tellus semper dapibus.", rating: 5, product_id: 9, user_id: 3)
Review.create(content: "In eu eros eu ex malesuada condimentum. Nunc ut lacus consectetur, pretium nisl et, vehicula sapien. Cras mollis quam mattis tellus semper dapibus.", rating: 5, product_id: 9, user_id: 4)

